spring.application.name=InfoMaisSaude
api.security.token.secret=2d0fe14e-8878-4d6a-896c-5e5171f63aca
# ===================================================================
# CONFIGURAÇÕES DO BANCO DE DADOS - POSTGRESQL (Ambiente de Desenvolvimento)
# ===================================================================
# URL de conexão JDBC para o PostgreSQL.
# localhost:5433 é o endereço
spring.datasource.url=jdbc:postgresql://localhost:5433/InfoMaisSaude-ModuloAdministrativo
# Usuário padrão do PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=andreysantos12
# ===================================================================
# CONFIGURAÇÕES DO JPA/HIBERNATE
# ===================================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ===================================================================
# SENHA DO TOKEN JWT
# ===================================================================
api.security.token.secret=002a58fb-5209-4a03-8b06-1d5a9e489ce8
# ===================================================================
# HABILITANDO O DEBUG DO SPRING SECURITY 
# ===================================================================
logging.level.org.springframework.security=DEBUG




